" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" LSP
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'mattn/vim-lsp-icons'

Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'

Plug 'elixir-editors/vim-elixir'

" Visual
Plug 'itchyny/lightline.vim'
Plug 'cocopon/iceberg.vim'
Plug 'luochen1990/rainbow'
Plug 'mechatroner/rainbow_csv'

" Finder
Plug 'mileszs/ack.vim'
Plug 'justinmk/vim-dirvish'
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'

call plug#end()

" lightline

set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'iceberg',
      \ }

" color

"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

syntax enable
colorscheme iceberg
let g:rainbow_active = 1
set listchars=trail:-,nbsp:+,tab:>.
set list
set number
set expandtab
set tabstop=2
set shiftwidth=2

" fast esc
if ! has('gui_running')
    set ttimeoutlen=10
    augroup FastEscape
        autocmd!
        au InsertEnter * set timeoutlen=0
        au InsertLeave * set timeoutlen=1000
    augroup END
endif

" clipboard

if has('mac')
  set clipboard=unnamed
endif

" the silver searcher
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" swp/backup/undo
set backupdir=~/.vimbackup
set directory=~/.vimswp
set undodir=~/.vimundo

