#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [ "$(uname)" = 'Darwin' ]; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -Uz history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

alias vi="vim"
export EDITOR="vim"

eval "$(direnv hook zsh)"

## Command history configuration
#
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt hist_ignore_dups     # ignore duplication command history list
setopt share_history        # share command history data

HISTTIMEFORMAT="[%Y/%M/%D %H:%M:%S] "

export CLICOLOR=1
setopt correct

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ "$(uname)" = 'Darwin' ]; then
  if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

    autoload -Uz compinit
    compinit
  fi
fi

source ~/.zshrc.mine

